version: 2
jobs:
  test:
    docker:
    - image: circleci/golang:1.15

    steps:
    - checkout
    - run:
        name: Run unit tests
        command: go test ./...

workflows:
  version: 2
  build-workflow:
    jobs:
      - build
