version: 2.1
orbs:
  win: circleci/windows@2.2.0

jobs:
  test:
    docker:
    - image: circleci/golang:1.15

    steps:
    - checkout
    - run:
        name: Run unit tests
        command: go test ./...

  test-macos:
    macos:
      xcode: 11.7.0
    steps:
      - checkout
      - go test ./...

  test-windows:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
    - checkout
    - run: go test./...

workflows:
  version: 2
  unit-test-workflow:
    jobs:
    - test
    - test-macos
    - test-windows
