version: 2.1
orbs:
  win: circleci/windows@2.2.0

jobs:
  style:
    docker:
      - image: circleci/golang:1.15
    steps:
      - run: go vet ./...
      - run: $(go fmt ./... | wc -l) || exit 1

  test:
    docker:
    - image: circleci/golang:1.15

    steps:
    - checkout
    - run: go test ./...

# another support plan necessary
# test-macos:
#   macos:
#     xcode: 11.7.0
#   steps:
#   - checkout
#   - run: go test ./...

  test-windows:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
    - checkout
    - run: choco install make
    - run: choco install golang --version 1.15
    - run: go test ./...

  integration:
    docker:
    - image: circleci/golang:1.15
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run: docker run hello-world

  integration-windows:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
    - checkout
    - run: choco install make
    - run: docker run hello-world

  release:
    docker:
      - image: circleci/golang:1.15
    steps:
      - checkout
      - run: go get github.com/github-release/github-release

workflows:
  version: 2
  unit-test-workflow:
    jobs:
    - style
    - test
    - test-windows
    - integration
    - integration-windows
    - release
        requires:
        - style
        - test
        - test-windows
        - integration
        - integration-windows
      filters:
        branches:
          only:
            # - main
            - master
        tags:
          only: /^v.*/
